name: Build and Test (.NET 9)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ModularMonolith.Template.sln

      - name: Build Auth.API module
        run: dotnet build src/Modules/Auth/Auth.API/Auth.API.csproj --configuration Release --no-restore

      - name: Build Users.API module
        run: dotnet build src/Modules/Users/Users.API/Users.API.csproj --configuration Release --no-restore

      # Upload the modular build outputs (adjust paths as needed)
      - name: Upload modules build output
        uses: actions/upload-artifact@v4
        with:
          name: modules-build-output
          path: |
            src/Modules/Auth/Auth.API/bin/Release/net9.0/
            src/Modules/Users/Users.API/bin/Release/net9.0/

  build-main-api:
    runs-on: ubuntu-latest
    needs: build-modules
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Download modular build outputs
      - name: Download modules build output
        uses: actions/download-artifact@v4
        with:
          name: modules-build-output
          path: ./modules

      - name: Restore dependencies
        run: dotnet restore ModularMonolith.Template.sln

      # Make sure modular DLLs are available for main API build (copy or reference as needed)

      - name: Build ModularMonolith.Template.Api
        run: dotnet build src/ModularMonolith.Template.Api/ModularMonolith.Template.Api.csproj --configuration Release --no-restore

      # Upload main API build output
      - name: Upload main api build output
        uses: actions/upload-artifact@v4
        with:
          name: main-api-build-output
          path: src/ModularMonolith.Template.Api/bin/Release/net9.0/

  build-and-test:
    runs-on: ubuntu-latest
    needs: build-main-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Download main API build outputs
      - name: Download main api build output
        uses: actions/download-artifact@v4
        with:
          name: main-api-build-output
          path: ./mainapi

      - name: Restore dependencies
        run: dotnet restore ModularMonolith.Template.sln

      - name: Build Tests
        run: dotnet build tests/ModularMonolith.Template.Application.Tests.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test tests/ModularMonolith.Template.Application.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"
