name: Build and Test (.NET 9)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ModularMonolith.Template.sln

      - name: Build Auth.API module
        run: dotnet build src/Modules/Auth/Auth.API/Auth.API.csproj --configuration Release --no-restore

      - name: Build Users.API module
        run: dotnet build src/Modules/Users/Users.API/Users.API.csproj --configuration Release --no-restore

  build-main-api:
    runs-on: ubuntu-latest
    needs: build-modules
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build ModularMonolith.Template.Api
        run: dotnet build src/ModularMonolith.Template.Api/ModularMonolith.Template.Api.csproj --configuration Release --no-restore

  build-and-test:
    runs-on: ubuntu-latest
    needs: build-main-api
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build Tests
        run: dotnet build tests/ModularMonolith.Template.Application.Tests.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test tests/ModularMonolith.Template.Application.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

